export const pageEditorId = 'UGFnZUVkaXRvcjox'
export const scapholdUrl = 'us-west-2.api.scaphold.io/graphql/tmms-dev'
export const auth0ClientId = '8pxfV8tkdBxczd1t643oQi9E33DiTtp4'
export const auth0Domain = 'tmt.eu.auth0.com'
export const auth0CallbackUrl = 'exp://jf-wev.dadtmt.tmms-client-14.exp.direct:80/+/redirect'
